"""remove contract price app_users

Revision ID: 050f5ba66772
Revises: 8efa8a538cfb
Create Date: 2018-10-02 17:32:50.281618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050f5ba66772'
down_revision = '8efa8a538cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_users_contract_price', table_name='app_users')
    op.drop_column('app_users', 'contract_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('contract_price', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('ix_app_users_contract_price', 'app_users', ['contract_price'], unique=True)
    # ### end Alembic commands ###
