"""redo change routes

Revision ID: 38dabcee7fd3
Revises: eedca093db61
Create Date: 2018-09-22 14:23:52.534462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38dabcee7fd3'
down_revision = 'eedca093db61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_routes_code'), 'routes', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_code'), table_name='routes')
    op.drop_column('routes', 'code')
    # ### end Alembic commands ###
