"""alter collections add farmer_no

Revision ID: 3a81b30c4862
Revises: 23e79d371587
Create Date: 2018-10-03 12:45:02.121633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a81b30c4862'
down_revision = '23e79d371587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('farmer_id', sa.Integer(), nullable=True))
    op.drop_constraint('collections_farmer_no_fkey', 'collections', type_='foreignkey')
    op.create_foreign_key(None, 'collections', 'farmers', ['farmer_id'], ['id'])
    op.drop_column('collections', 'farmer_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('farmer_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.create_foreign_key('collections_farmer_no_fkey', 'collections', 'farmers', ['farmer_no'], ['id'])
    op.drop_column('collections', 'farmer_id')
    # ### end Alembic commands ###
