"""initial migration

Revision ID: 69de93e607ae
Revises: 
Create Date: 2018-10-01 11:58:50.717666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69de93e607ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_factories_code'), 'factories', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factories_code'), table_name='factories')
    op.drop_column('factories', 'code')
    # ### end Alembic commands ###
