"""change factory code to number

Revision ID: 77ba38407755
Revises: 69de93e607ae
Create Date: 2018-10-02 10:29:50.963637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ba38407755'
down_revision = '69de93e607ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('number', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_factories_number'), 'factories', ['number'], unique=True)
    op.drop_index('ix_factories_code', table_name='factories')
    op.drop_column('factories', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('ix_factories_code', 'factories', ['code'], unique=True)
    op.drop_index(op.f('ix_factories_number'), table_name='factories')
    op.drop_column('factories', 'number')
    # ### end Alembic commands ###
