"""undo change routes

Revision ID: 7e193cda03fa
Revises: 38dabcee7fd3
Create Date: 2018-09-22 14:33:07.556314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e193cda03fa'
down_revision = '38dabcee7fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_routes_code', table_name='routes')
    op.drop_column('routes', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('ix_routes_code', 'routes', ['code'], unique=True)
    # ### end Alembic commands ###
