"""add processor type

Revision ID: 8efa8a538cfb
Revises: 77ba38407755
Create Date: 2018-10-02 12:10:37.533138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efa8a538cfb'
down_revision = '77ba38407755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processors', sa.Column('type', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_processors_type'), 'processors', ['type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processors_type'), table_name='processors')
    op.drop_column('processors', 'type')
    # ### end Alembic commands ###
