"""add start-end in db routes

Revision ID: a0016039de62
Revises: 2c01953074ba
Create Date: 2018-09-22 20:32:25.426632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0016039de62'
down_revision = '2c01953074ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('end', sa.String(length=64), nullable=True))
    op.add_column('routes', sa.Column('start', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_routes_end'), 'routes', ['end'], unique=False)
    op.create_index(op.f('ix_routes_start'), 'routes', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_start'), table_name='routes')
    op.drop_index(op.f('ix_routes_end'), table_name='routes')
    op.drop_column('routes', 'start')
    op.drop_column('routes', 'end')
    # ### end Alembic commands ###
