"""empty message

Revision ID: b409a52b8938
Revises: 
Create Date: 2017-10-28 09:49:24.875888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b409a52b8938'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('grader_payment_status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_trips_grader_payment_status'), 'trips', ['grader_payment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_grader_payment_status'), table_name='trips')
    op.drop_column('trips', 'grader_payment_status')
    # ### end Alembic commands ###
