"""alter collections add farmer_no

Revision ID: dea951c3341d
Revises: 
Create Date: 2018-10-03 12:35:42.787707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea951c3341d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('farmer_no', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collections', 'farmers', ['farmer_no'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_column('collections', 'farmer_no')
    # ### end Alembic commands ###
