"""change routes

Revision ID: eedca093db61
Revises: 1389781e6ad5
Create Date: 2018-09-22 13:33:11.778480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedca093db61'
down_revision = '1389781e6ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_factories_code', table_name='factories')
    op.drop_column('factories', 'code')
    op.drop_index('ix_routes_code', table_name='routes')
    op.drop_column('routes', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('ix_routes_code', 'routes', ['code'], unique=True)
    op.add_column('factories', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('ix_factories_code', 'factories', ['code'], unique=True)
    # ### end Alembic commands ###
