"""empty message

Revision ID: f98bb45a1e28
Revises: dae77168dc32
Create Date: 2017-10-29 16:43:23.707842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f98bb45a1e28'
down_revision = 'dae77168dc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grader_payments', sa.Column('grader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grader_payments', 'app_users', ['grader_id'], ['id'])
    op.drop_column('grader_payments', 'gross')
    op.drop_column('grader_payments', 'net')
    op.add_column('trips', sa.Column('payment_generated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'payment_generated')
    op.add_column('grader_payments', sa.Column('net', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('grader_payments', sa.Column('gross', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grader_payments', type_='foreignkey')
    op.drop_column('grader_payments', 'grader_id')
    # ### end Alembic commands ###
